[theme]
base = "light"
primaryColor = "#667eea"
backgroundColor = "#ffffff" 
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[logger]
level = "info"

[client]
toolbarMode = "minimal"
showErrorDetails = false